# Site settings
title: SmallBASIC Language reference
email: smallbasic@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  SmallBASIC is a fast and easy to learn BASIC language interpreter ideal for
  everyday calculations, scripts and prototypes. SmallBASIC includes trigonometric,
  matrices and algebra functions, a built in IDE, a powerful string library,
  system, sound, and graphic commands along with structured programming syntax.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://smallbasic.sourceforge.net"
github_username:  smallbasic

# Build settings
markdown: kramdown

relative_permalinks: false
